services:
  - type: web
    name: retgistratura
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn retgistratura.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DJANGO_SETTINGS_MODULE
        value: retgistratura.settings_prod
      - key: SECRET_KEY
        value: django-insecure-your-secret-key-here
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: retgistratura.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: retgistratura-db
          property: connectionString
      - key: CSRF_TRUSTED_ORIGINS
        value: https://retgistratura.onrender.com
      - key: STATIC_URL
        value: /static/
      - key: STATIC_ROOT
        value: staticfiles
      - key: MEDIA_URL
        value: /media/
      - key: MEDIA_ROOT
        value: media

databases:
  - name: retgistratura-db
    databaseName: retgistratura
    user: retgistratura
    plan: free 