# Generated by Django 5.1.7 on 2025-04-10 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название отделения')),
                ('description', models.TextField(blank=True, verbose_name='Описание отделения')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('room_number', models.CharField(max_length=10, verbose_name='Номер кабинета')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('specialization', models.CharField(max_length=100, verbose_name='Специализация')),
                ('experience_years', models.IntegerField(verbose_name='Опыт работы (лет)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors_photos/', verbose_name='Фото')),
                ('schedule', models.JSONField(default=dict, verbose_name='Расписание приёмов')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department', verbose_name='Отделение')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата приёма')),
                ('time', models.TimeField(verbose_name='Время приёма')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Запланирован'), ('COMPLETED', 'Завершён'), ('CANCELLED', 'Отменён')], default='SCHEDULED', max_length=20, verbose_name='Статус')),
                ('symptoms', models.TextField(blank=True, verbose_name='Симптомы')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Диагноз')),
                ('prescription', models.TextField(blank=True, verbose_name='Назначения')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Приём',
                'verbose_name_plural': 'Приёмы',
            },
        ),
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Медицинская услуга',
                'verbose_name_plural': 'Медицинские услуги',
            },
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.appointment', verbose_name='Приём')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.medicalservice', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга приёма',
                'verbose_name_plural': 'Услуги приёма',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('medical_history', models.TextField(blank=True, verbose_name='История болезни')),
                ('insurance_number', models.CharField(max_length=20, verbose_name='Номер страхового полиса')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient', verbose_name='Пациент'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата платежа')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('COMPLETED', 'Оплачено'), ('CANCELLED', 'Отменено')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Способ оплаты')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.appointment', verbose_name='Приём')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PATIENT', 'Пациент'), ('DOCTOR', 'Врач'), ('ADMIN', 'Администратор')], default='PATIENT', max_length=20, verbose_name='Роль пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
